variables = {}
variables["4j_ge3t"] = [
    'Evt_blr_ETH',
    'Evt_Dr_TaggedJetsAverage',
    'Evt_CSV_Dev',
    'Evt_JetPtOverJetE',
    'BDT_common5_input_avg_dr_tagged_jets',
    'Evt_CSV_Average_Tagged',
    'Evt_Dr_JetsAverage',
    'Evt_M_JetsAverage',
    'CSV[2]',
    'Evt_CSV_Min',
    'Evt_M_MinDeltaRLeptonTaggedJet',
    'CSV[3]',
    'Evt_CSV_Average',
    'Jet_Pt[0]',
    'Evt_blr_ETH_transformed',
    'Evt_HT_tagged',
    'Evt_Deta_JetsAverage',
    'Evt_M2_TaggedJetsAverage',
    'Evt_M_TaggedJetsAverage',
    'Evt_HT',
    ]

variables["5j_ge3t"] = [
    'Evt_CSV_Dev_Tagged',
    'Evt_Dr_TaggedJetsAverage',
    'Evt_Deta_TaggedJetsAverage',
    'Evt_CSV_Dev',
    'Evt_M_MinDeltaRLeptonTaggedJet',
    'Evt_blr_ETH',
    'BDT_common5_input_h1',
    'Evt_CSV_Min_Tagged',
    'CSV[2]',
    'CSV[3]',
    'Evt_CSV_Average_Tagged',
    'Evt_HT_tagged',
    'Jet_Pt[0]',
    'Evt_M_JetsAverage',
    'Evt_M2_TaggedJetsAverage',
    'Evt_Deta_JetsAverage',
    'Evt_blr_ETH_transformed',
    'Evt_CSV_Average',
    'Evt_HT',
    'Evt_M_TaggedJetsAverage',
    ]

variables["6j_ge3t"] = [
    'Evt_Deta_TaggedJetsAverage',
    'Evt_M_MinDeltaRLeptonTaggedJet',
    'Jet_Pt[2]',
    'BDT_common5_input_h1',
    'Evt_CSV_Min',
    'Evt_blr_ETH',
    'Jet_Pt[0]',
    'N_BTagsM',
    'Evt_CSV_Average_Tagged',
    'Evt_HT_tagged',
    'Evt_M2_TaggedJetsAverage',
    'CSV[3]',
    'Evt_M_JetsAverage',
    'CSV[2]',
    'Evt_blr_ETH_transformed',
    'Evt_Deta_JetsAverage',
    'Evt_CSV_Dev',
    'Evt_HT',
    'Evt_CSV_Average',
    'Evt_M_TaggedJetsAverage',
    ]

variables["ge6j_ge3t"] = [
    'Evt_CSV_Min_Tagged',
    'Evt_Dr_MinDeltaRTaggedJets',
    'Evt_Deta_TaggedJetsAverage',
    'Evt_M_MinDeltaRTaggedJets',
    'Jet_Pt[0]',
    'Evt_blr_ETH',
    'Evt_M_MinDeltaRLeptonTaggedJet',
    'N_BTagsL',
    'Evt_M2_TaggedJetsAverage',
    'Evt_CSV_Average_Tagged',
    'Evt_Deta_JetsAverage',
    'Evt_CSV_Average',
    'Evt_M_JetsAverage',
    'CSV[2]',
    'CSV[3]',
    'Evt_HT_tagged',
    'N_BTagsM',
    'Evt_CSV_Dev',
    'Evt_HT',
    'Evt_blr_ETH_transformed',
    'Evt_M_TaggedJetsAverage',
    ]

variables["ge7j_ge3t"] = [
    'Jet_Pt[0]',
    'N_BTagsL',
    'BDT_common5_input_sphericity_jets',
    'Evt_Dr_TaggedJetsAverage',
    'Evt_JetPtOverJetE',
    'Evt_Deta_TaggedJetsAverage',
    'Evt_M2_TaggedJetsAverage',
    'Evt_blr_ETH',
    'Evt_CSV_Average_Tagged',
    'Evt_HT_tagged',
    'Evt_M_MinDeltaRLeptonTaggedJet',
    'Evt_M_JetsAverage',
    'Evt_Deta_JetsAverage',
    'Evt_CSV_Average',
    'Evt_HT',
    'CSV[2]',
    'N_BTagsM',
    'Evt_blr_ETH_transformed',
    'Evt_CSV_Dev',
    'CSV[3]',
    'Evt_M_TaggedJetsAverage',
    ]

variables["le5j_ge3t"] = [
    'Evt_M_MinDeltaRTaggedJets',
    'Evt_CSV_Dev_Tagged',
    'Evt_Dr_MinDeltaRLeptonTaggedJet',
    'BDT_common5_input_avg_dr_tagged_jets',
    'BDT_common5_input_h1',
    'Evt_M_MinDeltaRLeptonTaggedJet',
    'Evt_Dr_JetsAverage',
    'Evt_CSV_Dev',
    'Evt_blr_ETH',
    'Evt_CSV_Average_Tagged',
    'Evt_CSV_Average',
    'CSV[2]',
    'CSV[3]',
    'Jet_Pt[0]',
    'Evt_HT_tagged',
    'Evt_blr_ETH_transformed',
    'Evt_M2_TaggedJetsAverage',
    'Evt_Deta_JetsAverage',
    'Evt_HT',
    'Evt_M_TaggedJetsAverage',
    ]

variables["le6j_ge3t"] = [
    'Jet_Pt[1]',
    'Evt_Deta_TaggedJetsAverage',
    'BDT_common5_input_h1',
    'Evt_M_JetsAverage',
    'N_BTagsM',
    'Evt_M_MinDeltaRLeptonTaggedJet',
    'N_BTagsL',
    'Jet_Pt[0]',
    'Evt_blr_ETH',
    'Evt_CSV_Average_Tagged',
    'Evt_CSV_Dev',
    'CSV[2]',
    'CSV[3]',
    'Evt_Deta_JetsAverage',
    'Evt_M2_TaggedJetsAverage',
    'Evt_HT_tagged',
    'Evt_CSV_Average',
    'Evt_blr_ETH_transformed',
    'Evt_HT',
    'Evt_M_TaggedJetsAverage',
    ]

variables["ge4j_ge3t"] = [
    'BDT_common5_input_h1',
    'Evt_Deta_TaggedJetsAverage',
    'Evt_Dr_MinDeltaRLeptonTaggedJet',
    'Evt_JetPtOverJetE',
    'Evt_CSV_Dev',
    'Evt_M_MinDeltaRTaggedJets',
    'N_BTagsL',
    'Evt_blr_ETH',
    'Jet_Pt[0]',
    'Evt_CSV_Average',
    'CSV[2]',
    'Evt_M2_TaggedJetsAverage',
    'Evt_CSV_Average_Tagged',
    'N_BTagsM',
    'Evt_Deta_JetsAverage',
    'CSV[3]',
    'Evt_HT_tagged',
    'Evt_blr_ETH_transformed',
    'Evt_HT',
    'Evt_M_TaggedJetsAverage',
    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
