
variables = {}
variables["4j_ge3t"] = [
    'Jet_Pt[0]',
    'Jet_CSV[0]',
    'Jet_CSV[1]',
    'Jet_CSV[2]',
    'Jet_Pt[3]',
    'Jet_CSV[3]',
    'Evt_Dr_MinDeltaRTaggedJets',
    'Evt_Dr_TaggedJetsAverage',
    'Evt_CSV_Average',
    'Evt_CSV_Average_Tagged',
    'CSV[0]',
    'CSV[1]',
    'Evt_CSV_Min',
    'Evt_CSV_Min_Tagged',
    'Evt_M_MinDeltaRLeptonTaggedJet',
    'Evt_M_JetsAverage',
    'Evt_M2_TaggedJetsAverage',
    'Evt_HT',
    'N_BTagsT',
    'N_BTagsM',
    'N_BTagsL',
    'Evt_blr_ETH',
    'Evt_blr_ETH_transformed',
    ]

variables["5j_ge3t"] = [
    'Jet_Pt[0]',
    'Jet_CSV[0]',
    'Jet_CSV[1]',
    'Jet_CSV[2]',
    'Jet_Pt[3]',
    'Jet_CSV[3]',
    'Evt_Dr_MinDeltaRTaggedJets',
    'Evt_Dr_TaggedJetsAverage',
    'Evt_CSV_Average',
    'Evt_CSV_Average_Tagged',
    'CSV[0]',
    'CSV[1]',
    'Evt_CSV_Min',
    'Evt_CSV_Min_Tagged',
    'Evt_M_MinDeltaRLeptonTaggedJet',
    'Evt_M_JetsAverage',
    'Evt_M2_TaggedJetsAverage',
    'Evt_HT',
    'N_BTagsT',
    'N_BTagsM',
    'N_BTagsL',
    'Evt_blr_ETH',
    'Evt_blr_ETH_transformed',
    ]

variables["ge6j_ge3t"] = [
    'Jet_Pt[0]',
    'Jet_CSV[0]',
    'Jet_CSV[1]',
    'Jet_CSV[2]',
    'Jet_Pt[3]',
    'Jet_CSV[3]',
    'Evt_Dr_MinDeltaRTaggedJets',
    'Evt_Dr_TaggedJetsAverage',
    'Evt_CSV_Average',
    'Evt_CSV_Average_Tagged',
    'CSV[0]',
    'CSV[1]',
    'Evt_CSV_Min',
    'Evt_CSV_Min_Tagged',
    'Evt_M_MinDeltaRLeptonTaggedJet',
    'Evt_M_JetsAverage',
    'Evt_M2_TaggedJetsAverage',
    'Evt_HT',
    'N_BTagsT',
    'N_BTagsM',
    'N_BTagsL',
    'Evt_blr_ETH',
    'Evt_blr_ETH_transformed',
    ]

variables["le5j_ge3t"] = [
    'Jet_Pt[0]',
    'Jet_CSV[0]',
    'Jet_CSV[1]',
    'Jet_CSV[2]',
    'Jet_Pt[3]',
    'Jet_CSV[3]',
    'Evt_Dr_MinDeltaRTaggedJets',
    'Evt_Dr_TaggedJetsAverage',
    'Evt_CSV_Average',
    'Evt_CSV_Average_Tagged',
    'CSV[0]',
    'CSV[1]',
    'Evt_CSV_Min',
    'Evt_CSV_Min_Tagged',
    'Evt_M_MinDeltaRLeptonTaggedJet',
    'Evt_M_JetsAverage',
    'Evt_M2_TaggedJetsAverage',
    'Evt_HT',
    'N_BTagsT',
    'N_BTagsM',
    'N_BTagsL',
    'Evt_blr_ETH',
    'Evt_blr_ETH_transformed',
    ]

variables["6j_ge3t"] = [
    'Jet_Pt[0]',
    'Jet_CSV[0]',
    'Jet_CSV[1]',
    'Jet_CSV[2]',
    'Jet_Pt[3]',
    'Jet_CSV[3]',
    'Evt_Dr_MinDeltaRTaggedJets',
    'Evt_Dr_TaggedJetsAverage',
    'Evt_CSV_Average',
    'Evt_CSV_Average_Tagged',
    'CSV[0]',
    'CSV[1]',
    'Evt_CSV_Min',
    'Evt_CSV_Min_Tagged',
    'Evt_M_MinDeltaRLeptonTaggedJet',
    'Evt_M_JetsAverage',
    'Evt_M2_TaggedJetsAverage',
    'Evt_HT',
    'N_BTagsT',
    'N_BTagsM',
    'N_BTagsL',
    'Evt_blr_ETH',
    'Evt_blr_ETH_transformed',
    ]

variables["ge7j_ge3t"] = [
    'Jet_Pt[0]',
    'Jet_CSV[0]',
    'Jet_CSV[1]',
    'Jet_CSV[2]',
    'Jet_Pt[3]',
    'Jet_CSV[3]',
    'Evt_Dr_MinDeltaRTaggedJets',
    'Evt_Dr_TaggedJetsAverage',
    'Evt_CSV_Average',
    'Evt_CSV_Average_Tagged',
    'CSV[0]',
    'CSV[1]',
    'Evt_CSV_Min',
    'Evt_CSV_Min_Tagged',
    'Evt_M_MinDeltaRLeptonTaggedJet',
    'Evt_M_JetsAverage',
    'Evt_M2_TaggedJetsAverage',
    'Evt_HT',
    'N_BTagsT',
    'N_BTagsM',
    'N_BTagsL',
    'Evt_blr_ETH',
    'Evt_blr_ETH_transformed',
    ]

variables["ge4j_ge3t"] = [
    'Jet_Pt[0]',
    'Jet_CSV[0]',
    'Jet_CSV[1]',
    'Jet_CSV[2]',
    'Jet_Pt[3]',
    'Jet_CSV[3]',
    'Evt_Dr_MinDeltaRTaggedJets',
    'Evt_Dr_TaggedJetsAverage',
    'Evt_CSV_Average',
    'Evt_CSV_Average_Tagged',
    'CSV[0]',
    'CSV[1]',
    'Evt_CSV_Min',
    'Evt_CSV_Min_Tagged',
    'Evt_M_MinDeltaRLeptonTaggedJet',
    'Evt_M_JetsAverage',
    'Evt_M2_TaggedJetsAverage',
    'Evt_HT',
    'N_BTagsT',
    'N_BTagsM',
    'N_BTagsL',
    'Evt_blr_ETH',
    'Evt_blr_ETH_transformed',
    ]


all_variables = set( [v for key in variables for v in variables[key] ] )
