#python plotInputVariables.py nominal lumi_13TeVUp all 1.023
#python plotInputVariables.py nominal lumi_13TeVDown all 0.977
#python plotInputVariables.py nominal QCDscale_ttHHUp ttHH4b 1.015
#python plotInputVariables.py nominal QCDscale_ttHHDown ttHH4b 0.957
python plotInputVariables.py nominal QCDscale_ttbarUp ttbar 1.02
python plotInputVariables.py nominal QCDscale_ttbarDown ttbar 0.96
#python plotInputVariables.py nominal QCDscale_singletUp SingleTop 1.031
#python plotInputVariables.py nominal QCDscale_singletDown SingleTop 0.979
#python plotInputVariables.py nominal pdf_ggUp ttbar 1.04
#python plotInputVariables.py nominal pdf_ggDown ttbar 0.96
#python plotInputVariables.py nominal pdf_qgUp SingleTop 0.028
#python plotInputVariables.py nominal pdf_qgDown SingleTop 0.972
#python plotInputVariables.py nominal pdf_Higgs_ttHHUp ttHH4b 1.032
#python plotInputVariables.py nominal pdf_Higgs_ttHHDown ttHH4b 0.968
python plotInputVariables.py nominal QCDscale_ttHbbUp ttHbb 1.058
python plotInputVariables.py nominal QCDscale_ttHbbDown ttHbb 0.908
python plotInputVariables.py nominal pdf_Higgs_ttHbbUp ttHbb 1.036
python plotInputVariables.py nominal pdf_Higgs_ttHbbDown ttHbb 0.964
#python plotInputVariables.py nominal CMS_ttHbb_bgnorm_ttbarPlus2B_2017Up tt2b 1.5
#python plotInputVariables.py nominal CMS_ttHbb_bgnorm_ttbarPlus2B_2017Down tt2b 0.5
#python plotInputVariables.py nominal CMS_ttHbb_bgnorm_ttbarPlusBBbar_2017Up ttbb 1.5
#python plotInputVariables.py nominal CMS_ttHbb_bgnorm_ttbarPlusBBbar_2017Down ttbb 0.5
#python plotInputVariables.py nominal CMS_ttHbb_bgnorm_ttbarPlusB_2017Up ttb 1.5
#python plotInputVariables.py nominal CMS_ttHbb_bgnorm_ttbarPlusB_2017Down ttb 0.5
##python plotInputVariables.py nominal CMS_ttHbb_bgnorm_ttbarPlusCCbar_2017Up ttcc 1.5
#python plotInputVariables.py nominal CMS_ttHbb_bgnorm_ttbarPlusCCbar_2017Down ttcc 0.5
