python plotInputVariables.py nominal
python plotInputVariables.py JESUp
python plotInputVariables.py JESDown
python plotInputVariables.py JERUp
python plotInputVariables.py JERDown


#nominal is used as a variation for creating the extra systematics.
#systematics coming from n-tuples: see above. They don't need the second input argument.
#if second input argument is empty, it uses only the variation of the ntuple.
#if not nominal, do things!
python plotInputVariables.py nominal Weight_CSVCErr1down
python plotInputVariables.py nominal Weight_CSVCErr1up
python plotInputVariables.py nominal Weight_CSVCErr2down
python plotInputVariables.py nominal Weight_CSVCErr2up
python plotInputVariables.py nominal Weight_CSVHFdown
python plotInputVariables.py nominal Weight_CSVHFup
python plotInputVariables.py nominal Weight_CSVHFStats1down
python plotInputVariables.py nominal Weight_CSVHFStats1up
python plotInputVariables.py nominal Weight_CSVHFStats2down
python plotInputVariables.py nominal Weight_CSVHFStats2up
python plotInputVariables.py nominal Weight_CSVLFdown
python plotInputVariables.py nominal Weight_CSVLFup
python plotInputVariables.py nominal Weight_CSVLFStats1down
python plotInputVariables.py nominal Weight_CSVLFStats1up
python plotInputVariables.py nominal Weight_CSVLFStats2down
python plotInputVariables.py nominal Weight_CSVLFStats2up
python plotInputVariables.py nominal Weight_pu69p2Down
python plotInputVariables.py nominal Weight_pu69p2Up
python plotInputVariables.py nominal Weight_ElectronSFGFS_Down
python plotInputVariables.py nominal Weight_ElectronSFGFS_Up
python plotInputVariables.py nominal Weight_ElectronSFID_Down
python plotInputVariables.py nominal Weight_ElectronSFID_Up
python plotInputVariables.py nominal Weight_ElectronSFTrigger_Down
python plotInputVariables.py nominal Weight_ElectronSFTrigger_Up
python plotInputVariables.py nominal Weight_MuonSFID_Down
python plotInputVariables.py nominal Weight_MuonSFID_Up
python plotInputVariables.py nominal Weight_MuonSFIso_Up
python plotInputVariables.py nominal Weight_MuonSFIso_Down
python plotInputVariables.py nominal Weight_MuonSFTrigger_Down
python plotInputVariables.py nominal Weight_MuonSFTrigger_Up
python plotInputVariables.py nominal GenWeight_8
python plotInputVariables.py nominal GenWeight_6
python plotInputVariables.py nominal GenWeight_9
python plotInputVariables.py nominal GenWeight_7
python plotInputVariables.py nominal Weight_LHA_306000_up
python plotInputVariables.py nominal Weight_LHA_306000_down
python plotInputVariables.py nominal Weight_scale_variation_muR_2p0_muF_1p0
python plotInputVariables.py nominal Weight_scale_variation_muR_0p5_muF_1p0
python plotInputVariables.py nominal Weight_scale_variation_muR_1p0_muF_2p0
python plotInputVariables.py nominal Weight_scale_variation_muR_1p0_muF_0p5
